import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = localFont({
  src: "../../public/fonts/Space_Grotesk/static/SpaceGrotesk-Regular.ttf",
  variable: "--font-space-grotesk",
  weight: "400",
});

const pixelifySans = localFont({
  src: "../../public/fonts/Pixelify_Sans/static/PixelifySans-Regular.ttf",
  variable: "--font-pixel",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Catch the Block",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} ${pixelifySans.variable} antialiased font-[family-name:var(--font-pixel)]`}
      >
        {children}
      </body>
    </html>
  );
}